// <auto-generated />
using System;
using ClothingPro.DataAccessLayer.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingPro.Migrations
{
    [DbContext(typeof(ClothingProContext))]
    [Migration("20240814031433_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingPro.DataAccessLayer.Model.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("ClothingPro.DataAccessLayer.Model.MenuHeader", b =>
                {
                    b.Property<int>("MenuHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuHeaderId"));

                    b.Property<int?>("MenuHeaderIsActive")
                        .HasColumnType("int");

                    b.Property<string>("MenuHeaderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StSortOrder")
                        .HasColumnType("int");

                    b.HasKey("MenuHeaderId");

                    b.ToTable("MenuHeader");
                });

            modelBuilder.Entity("ClothingPro.DataAccessLayer.Model.Stock", b =>
                {
                    b.Property<int>("StId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StId"));

                    b.Property<DateTime?>("StAddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StColour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StHSCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StInActive")
                        .HasColumnType("int");

                    b.Property<int?>("StIsOther")
                        .HasColumnType("int");

                    b.Property<int?>("StIsPant")
                        .HasColumnType("int");

                    b.Property<int?>("StIsPopular")
                        .HasColumnType("int");

                    b.Property<int?>("StIsShirt")
                        .HasColumnType("int");

                    b.Property<int?>("StMenuHeaderId")
                        .HasColumnType("int");

                    b.Property<string>("StName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StSortOrder")
                        .HasColumnType("int");

                    b.HasKey("StId");

                    b.ToTable("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
